#ANGLE -180 ~ +180
offset:
  ID1: 1.2
  ID2: 0
  ID3: 0
  ID4: 0.0
  ID5: 0
  ID6: 5.6
  ID7: 0
  ID8: 0
  ID9: 0
  ID10: 0
  ID11: 0
  ID12: 0
  ID13: 0
  ID14: 0
  ID15: 15
  ID16: 0
  ID17: 0
  ID18: 0
  ID19: 0
  ID20: 0
